import math
print ("How many students are there?")
n = int(input())
while (n>0):
	print ()
	print ("Hello! What Geometry Dimension do you chose?")
	print ("You have the following options:")
	print ("1. 2D")
	print ("2. 3D")
	print ("Enter the number beside it or the Geometry Dimension")
	gd = input()
	if (gd=='1' or gd=='2D' or gd=='2d'):
		print ("You have chosen 2D")
		print ("Pick a shape from the following options:")
		print ("1. Square")
		print ("2. Rectangle")
		print ("3. Rhombus")
		print ("4. Parallelogram")
		print ("5. Circle")
		print ("Enter the number beside it")
		s = input()
		if (s=='1'):
			print ("You chose a square")
			print ("Enter the side of the square")
			side = float(input())
			print ("The perimeter of the square is:", "{:.2f}".format(4*side))
			print ("The area of the square is:", "{:.2f}".format(side*side))
		if (s=='2'):
			print ("You chose a rectangle")
			print ("Enter the length of the rectangle")
			l = float(input())
			print ("Enter the breadth of the rectangle")
			b = float(input())
			print ("The perimeter of the rectangle is:", "{:.2f}".format(2*(l+b)))
			print ("The area of the rectangle is:", "{:.2f}".format(l*b))
		if (s=='3'):
			print ("You chose a rhombus")
			print ("Enter the side of the rhombus")
			side = float(input())
			print ("Enter the 1st diagonal of the rhombus")
			d1 = float(input())
			print ("Enter the 2nd diagonal of the rhombus")
			d2 = float(input())
			print ("The perimeter of the rhombus is:", "{:.2f}".format(4*side))
			print ("The area of the rhombus is:", "{:.2f}".format((d1*d2)/2))
		if (s=='4'):
			print ("You chose a parallelogram")
			print ("Enter the length of the parallelogram")
			l = float(input())
			print ("Enter the breadth of the parallelogram")
			b = float(input())
			print ("Enter the height of the parallelogram")
			h = float(input())
			print ("The perimeter of the parallelogram is:", "{:.2f}".format(2*(l+b)))
			print ("The area of the parallelogram is:", "{:.2f}".format(b*h))
		if (s=='5'):
			print ("You chose a circle")
			print ("Enter the radius of the circle")
			r = float(input())
			print ("The perimeter of the circle is:", "{:.2f}".format(2*math.pi*r))
			print ("The area of the circle is:", "{:.2f}".format(math.pi*r*r))
	if (gd=='2' or gd=='3D' or gd=='3d'):
		print ("You have chosen 3D")
		print ("Pick a shape from the following options:")
		print ("1. Cube")
		print ("2. Cuboid")
		print ("3. Right circular cone")
		print ("4. Hemisphere")
		print ("5. Sphere")
		print ("6. Solid cylinder")
		print ("7. Hollow cylinder")
		print ("Enter the number beside it")
		s = input()
		if(s=='1'):
			print ("You chose a cube")
			print ("Enter the side of the cube")
			side = float(input())
			print ("The CSA of the cube is:", "{:.2f}".format(4*side*side))
			print ("The TSA of the cube is:", "{:.2f}".format(6*side*side))
			print ("The volume of the cube is:", "{:.2f}".format(side*side*side))
		if(s=='2'):
			print ("You chose a cuboid")
			print ("Enter the length of the cuboid")
			l = float(input())
			print ("Enter the breadth of the cuboid")
			b = float(input())
			print ("Enter the height of the cuboid")
			h = float(input())
			print ("The CSA of the cuboid is:", "{:.2f}".format(2*(l+b)*h))
			print ("The TSA of the cuboid is:", "{:.2f}".format(2*(l*b+b*h+l*h)))
			print ("The volume of the cuboid is:", "{:.2f}".format(l*b*h))
		if(s=='3'):
			print ("You chose a right circular cone")
			print ("Enter the slant height of the right circular cone")
			l = float(input())
			print ("Enter the radius of the right circular cone")
			r = float(input())
			print ("Enter the height of the right circular cone")
			h = float(input())
			print ("The CSA of the right circular cone is:", "{:.2f}".format(math.pi*r*l))
			print ("The TSA of the right circular cone is:", "{:.2f}".format(math.pi*r*(r+l)))
			print ("The volume of the right circular cone is:", "{:.2f}".format((math.pi*r*r*h)/3))
		if(s=='4'):
			print ("You chose a hemisphere")
			print ("Enter the radius of the hemisphere")
			r = float(input())
			print ("The CSA of the hemisphere is:", "{:.2f}".format(2*math.pi*r*r))
			print ("The TSA of the hemisphere is:", "{:.2f}".format(3*math.pi*r*r))
			print ("The volume of the hemisphere is:", "{:.2f}".format((2/3)*math.pi*r*r*r))
		if(s=='5'):
			print ("You chose a sphere")
			print ("Enter the radius of the sphere")
			r = float(input())
			print ("The CSA of the sphere is:", "{:.2f}".format(4*math.pi*r*r))
			print ("The TSA of the sphere is:", "{:.2f}".format(4*math.pi*r*r))
			print ("The volume of the sphere is:", "{:.2f}".format((4/3)*math.pi*r*r*r))
		if(s=='6'):
			print ("You chose a solid cylinder")
			print ("Enter the radius of the solid cylinder")
			r = float(input())
			print ("Enter the height of the solid cylinder")
			h = float(input())
			print ("The CSA of the solid cylinder is:", "{:.2f}".format(2*math.pi*r*h))
			print ("The TSA of the solid cylinder is:", "{:.2f}".format(2*math.pi*r*(h+r)))
			print ("The volume of the solid cylinder is:", "{:.2f}".format(math.pi*r*r*h))
		if(s=='7'):
			print ("You chose a hollow cylinder")
			print ("Enter the outer radius of the hollow cylinder")
			r1 = float(input())
			print ("Enter the inner radius of the hollow cylinder")
			r2 = float(input())
			print ("Enter the height of the hollow cylinder")
			h = float(input())
			print ("The CSA of the hollow cylinder is:", "{:.2f}".format(2*math.pi*h*(r1+r2)))
			print ("The TSA of the hollow cylinder is:", "{:.2f}".format(2*math.pi*h*(r1+r2)+2*math.pi*(r1*r1-r2*r2)))
			print ("The volume of the hollow cylinder is:", "{:.2f}".format(math.pi*h*(r1*r1-r2*r2)))
	n = n-1